### ISSUE TITLE
Training code realease

### ISSUE THREAD

**Issue by ualiawan** [theNded/SGP#2]
Hello,

Thank you for sharing your work. I wanted to know when will the code be released and whether you will be sharing the training script along with evaluation code?

**Comment by besttangent** [comment]
same question.

**Comment by xuelunshen** [comment]
+1

**Comment by sitongan** [comment]
+1

**Comment by DJInori** [comment]
+1

**Comment by theNded** [comment]
Sorry I've been busy with several submissions and did not release as promised...
Let me set Sept 30 as the final ddl and release by that time!

**Comment by theNded** [comment]
Code uploaded. Feel free to submit issues w.r.t the code.
